# Generated by Django 5.1.3 on 2024-12-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_pair',
            field=models.CharField(max_length=7),
        ),
    ]
